"""Configuration file parser for Aizawa attractor simulations."""

from pathlib import Path
from typing import Dict, Any, List, Optional
import numpy as np


class ConfigManager:
    """Parse and manage configuration files for simulations."""
    
    @staticmethod
    def load(config_path: str) -> Dict[str, Any]:
        """
        Load configuration from file.
        
        File format:
            # Comments
            key = value
        
        Args:
            config_path: Path to configuration file
        
        Returns:
            Dictionary of configuration parameters
        """
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Config not found: {config_path}")
        
        config = {}
        
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                
                # Skip empty/comment lines
                if not line or line.startswith('#'):
                    continue
                
                if '=' not in line:
                    continue
                
                # Parse key = value
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                # Remove inline comments
                if '#' in value:
                    value = value.split('#')[0].strip()
                
                # Parse type
                config[key] = ConfigManager._parse_value(value)
        
        return config
    
    @staticmethod
    def _parse_value(value: str) -> Any:
        """Parse string to appropriate Python type."""
        # Boolean
        if value.lower() in ['true', 'false']:
            return value.lower() == 'true'
        
        # Handle initial conditions (semicolon-separated triplets)
        if ';' in value and ',' in value:
            triplets = value.split(';')
            conditions = []
            for triplet in triplets:
                coords = [float(x.strip()) for x in triplet.split(',')]
                conditions.append(np.array(coords))
            return conditions
        
        # Numeric
        try:
            if '.' in value or 'e' in value.lower():
                return float(value)
            else:
                return int(value)
        except ValueError:
            return value
    
    @staticmethod
    def save(config: Dict[str, Any], config_path: str):
        """
        Save configuration to file.
        
        Args:
            config: Configuration dictionary
            config_path: Output path
        """
        path = Path(config_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, 'w') as f:
            f.write("# Aizawa Attractor Configuration\n")
            f.write("# Generated by pattingalloang\n\n")
            
            for key, value in sorted(config.items()):
                if isinstance(value, bool):
                    value_str = 'true' if value else 'false'
                elif isinstance(value, float):
                    if abs(value) < 1e-4 or abs(value) > 1e4:
                        value_str = f"{value:.2e}"
                    else:
                        value_str = f"{value}"
                elif isinstance(value, list):
                    # Handle initial conditions
                    if isinstance(value[0], np.ndarray):
                        triplets = [','.join(map(str, ic)) for ic in value]
                        value_str = ';'.join(triplets)
                    else:
                        value_str = str(value)
                else:
                    value_str = str(value)
                
                f.write(f"{key} = {value_str}\n")
    
    @staticmethod
    def get_default_config() -> Dict[str, Any]:
        """Get default configuration."""
        return {
            'scenario_name': 'Standard Aizawa',
            'a': 0.95,
            'b': 0.7,
            'c': 0.6,
            'd': 3.5,
            'e': 0.25,
            'f': 0.1,
            'dt': 0.01,
            'n_steps': 80000,
            'transient_steps': 5000,
            'initial_x': 0.1,
            'initial_y': 0.0,
            'initial_z': 0.0,
            'seed': 42,
            'use_gpu': False,
            'compute_metrics': True,
            'save_csv': True,
            'save_netcdf': True,
            'save_png': True,
            'save_gif': True,
            'output_dir': 'outputs',
            'animation_fps': 30,
            'animation_dpi': 120,
            'animation_frames': 180,
            'animation_duration': 15.0,
            'png_dpi': 150,
        }
    
    @staticmethod
    def validate_config(config: Dict[str, Any]) -> bool:
        """
        Validate configuration parameters.
        
        Args:
            config: Configuration dictionary
        
        Returns:
            True if valid
        
        Raises:
            ValueError: If configuration is invalid
        """
        required_numeric = ['a', 'b', 'c', 'd', 'e', 'f', 'dt', 'n_steps']
        
        for key in required_numeric:
            if key not in config:
                raise ValueError(f"Missing required parameter: {key}")
        
        # Physical constraints
        if config.get('dt', 0) <= 0:
            raise ValueError("dt must be > 0")
        
        if config.get('n_steps', 0) < 100:
            raise ValueError("n_steps must be >= 100")
        
        return True
